query ($userId: bigint!) {
  users_by_pk(userId: $userId) {
    name
    currentGroupId
    scoreboardMemberships {
      scoreboardId
    }
  }
  games(where: {userGameRecords: {user: {userId: {_eq: $userId}}}}) {
    loserScore
    winnerScore
    timeOfGame
    userGameRecords {
      user {
        userId
        name
        email
      }
      gameOutcome
    }
  }
}
